const drMap = {
  // ==================== 分类（Category）名称 ====================
  Enemies: "敌人",
  Boss: "头目",
  Location: "地点",
  SoundTrack: "原声带",
  Vendors: "商店",
  Items: "物品",
  "Consumable items": "消耗品",
  Dog: "狗",
  "Gameplay Mechanics": "游戏机制",
  "Plot Elements": "戏情元素",
  Ending: "结局",
  "Neutral Route": "中立路线",
  "Genocide Route": "屠杀路线",
  "Pacifist Route": "完美路线",
  "Eight Human": "八名人类",

  // ==================== Deltarune 地点 ====================
  Hometown: "家乡镇",
  "Dreemurr residence": "Dreemurr家",
  School: "学校",
  Library: "图书馆",
  Hospital: "医院",
  "QC's Diner": "QC餐厅",
  "Town Hall": "市政厅",
  Shelter: "避难所",
  Church: "教堂",
  "'Sans": "'Sans便利店",
  "Noelle's House": "Holiday宅邸",
  "Closet Dark World": "学校储物间",
  "Party Dojo": "派对道场",
  "Ralsei's castle": "Ralsei的城堡",
  "TV Studio": "TV演播室",
  Field: "平原",
  Forest: "森林",
  "Card Castle": "扑克城堡",
  "Cyber Field": "赛博平原",
  "Cyber City": "赛博城市",
  "Queen's Mansion": "女王的豪宅",
  "TV World": "TV世界",
  "Couch cliffs": "沙发悬崖",
  "Green Room": "休息室",
  "Cold Place": "极寒之地",
  Mancountry: "男人国",
  "Desert Board": "沙漠图版",
  "Island Board": "岛屿图版",
  "Ice Palace": "冰宫",
  "City Board (Original Game)": "城市图版 (原版游戏)",
  "City Board (The Legend of Tenna)": "城市图版 (《Tenna传说》)",
  "Manhole dungeon": "下水道地牢",
  "Dark Sanctuaries": "三黑暗圣域",
  "Dark Sanctuary (Study)": "黑暗圣域 (书房)",
  "2nd Sanctuary": "第二圣域",
  "3rd Sanctuary": "第三圣域",
  "Flower Kingdom": "花之王国",
  Garden: "花园",
  Cliffs: "悬崖",
  "Flower Castle (Flower Cafe)": "花之城堡 (花之咖啡馆)",
  "Top of Castle": "城堡顶层",
  Unused: "未使用",
  "Flower King": "花王",
  'ICE-E\'s P"E"ZZA': "ICE-E的披“E”萨店",
  "Police Station": "警察局",
  Lake: "湖",
  Cafe: "咖啡馆",
  "Top Bakery": "顶级面包店",
  "The Legend of Tenna": "《Tenna传说》",
  "Original Game": "原版游戏",
  "Wet-Nose Bandits": "湿鼻子大盗",
  // ==================== 新增物品、装备、机制等（按原列表顺序） ====================
  "Dark Candy": "黑暗糖果",
  Darkburger: "黑暗漢堡",
  "Choco Diamond": "方鑽巧克力",
  "Hearts Donut": "紅心甜甜圈",
  "Lancer Cookie": "Lancer餅乾",
  "Top Cake": "頂尖蛋糕",
  SpinCake: "旋轉蛋糕",
  ReviveMint: "復活薄荷",
  ClubsSandwich: "梅花三明治",
  RouxlsRoux: "Rouxls油麵醬",
  LightCandy: "光明糖果",
  "DD-Burger": "双黑堡",
  "CD Bagel": "CD貝果",
  TensionBit: "緊迫一點",
  Tea: "茶",
  SpagettiCode: "意面代码",
  "S.POISON": "S.毒藥",
  ReviveDust: "復活粉",
  TensionGem: "緊迫寶石",
  "TV Dinner": "電視餐",
  DeluxeDinner: "高檔餐",
  TVSlop: "電視糊糊",
  TensionMax: "緊迫滿點",
  ExecBuffet: "精英自助餐",
  "Pipis (item)": "Pipis (物品)",
  FlatSoda: "跑氣的汽水",
  "Darker Candy": "深暗糖果",
  AncientSweet: "遠古甜點",
  Rhapsotea: "狂想茶",
  Scarlixir: "緋紅靈藥",
  BitterTear: "苦澀眼淚",
  PunchBowl: "全碗潘趣",
  "S.POTION": "S.补药",
  GreenTea: "Green茶",
  OrangeJuice: "Orange果汁",
  Flavigne: "友怡颗粒",
  TreeCake: "年轮蛋糕",
  "Raw Moon": "梦芬达",
  Phanta: "潭珠汽水",
  FlowerySoda: "Flowery汽水",
  Shikacola: "鹿可乐",
  "Wood Blade": "木劍",
  Spookysword: "駭人的劍",
  MechaSaber: "機甲軍刀",
  BounceBlade: "彈彈劍",
  Saber10: "刺刀10",
  BlackShard: "黑色碎片",
  JingleBlade: "叮噹劍",
  "Winglade (item)": "羽翼劍",
  WoodBlade2: "木剑2",
  AquaKnife: "Aqua小刀",
  "Mane Ax": "鬃斧",
  Devilsknife: "惡魔飛刀",
  "Brave Ax": "勇氣之斧",
  AutoAxe: "自動斧",
  ToxicAxe: "劇毒斧",
  AbsorbAx: "吸取之斧",
  JusticeAxe: "正義之斧",
  Thatchet: "棘手斧",
  "Red Scarf": "紅圍巾",
  Ragger: "劈巾",
  DaintyScarf: "精緻圍巾",
  FiberScarf: "纖維圍巾",
  Ragger2: "劈巾2",
  PuppetScarf: "木偶圍巾",
  FlexScarf: "彎扭圍巾",
  ScarfMark: "絲籤圍巾",
  MistleWP: "槲寄生鞭",
  BlueShoes: "Blue舞鞋",
  BrokenScarf: "破围巾",
  SnowRing: "雪花指环",
  FreezeRing: "冰冻指环",
  ThornRing: "荊棘指环",
  BrokenSwd: "斷掉的劍",
  FloweryScarf: "Flowery围巾",
  Bandage: "创可贴",
  "White Ribbon": "白色緞帶",
  "Amber Card": "琥珀卡片",
  "Dice Brace": "骰子手鍊",
  IronShackle: "鐵製鐐銬",
  Jevilstail: "Jevil的尾巴",
  "Silver Card": "白銀卡片",
  GlowWrist: "彩燈手鍊",
  "Silver Watch": "銀色手錶",
  RoyalPin: "皇室胸針",
  "Pink Ribbon": "粉色緞帶",
  Mannequin: "假人模特",
  "B.ShotBowtie": "大××領結",
  FrayedBowtie: "殘破領結",
  ChainMail: "鏈鎖甲",
  Dealmaker: "成交神器",
  TwinRibbon: "成對緞帶",
  SpikeBand: "尖刺腕帶",
  TensionBow: "緊迫領結",
  LodeStone: "磁石",
  GingerGuard: "薑餅護盾",
  BlueRibbon: "藍色緞帶",
  TennaTie: "Tenna領帶",
  "Shadow Mantle": "暗影斗篷",
  Waferguard: "聖餅護盾",
  MysticBand: "神秘臂環",
  PowerBand: "力量臂環",
  GoldWidow: "金寡婦",
  PrincessRBN: "公主緞帶",
  MonarchRBN: "帝王缎带",
  TrueTie: "真领带",
  DogWidow: "狗寡妇",
  RedRibbon: "红色缎带",
  NetskieHat: "Netskie帽",
  SethSpecs: "Seth眼镜",
  YellowHat: "Yellow帽",
  "O.Glove": "O.手套",
  GreenApron: "Green围裙",
  "Cell Phone": "手機",
  "Broken Cake": "壞掉的蛋糕",
  "Broken Key": "鑰匙碎片",
  Egg: "蛋",
  "Door Key": "牢房鑰匙",
  "Shadow Crystal": "暗影水晶",
  "Lancer (item)": "Lancer (物品)",
  "Rouxls Kaard (item)": "Rouxls Kaard",
  "Starwalker (item)": "Starwalker",
  KeyGen: "密鑰生成器",
  EmptyDisk: "磁碟",
  OddController: "古怪手柄",
  LancerCon: "Lancer手柄",
  TripTicket: "旅行票",
  ClaimbClaws: "爬爬爪",
  SheetMusic: "樂譜",
  "Petal Feather": "花瓣羽毛",
  BromideR: "相卡R",
  YellowKey: "黄色钥匙",
  BlueString: "蓝色细绳",
  YellowShred: "黄色碎布",
  BootOil: "靴油",
  Scissors: "剪刀",
  PerpBook: "紫证书",
  TrainPlan: "轨道设计图",
  RedSplatter: "红色喷溅物",
  MysteryKey: "神秘钥匙",
  BromideF: "相卡F",
  "Key (The Legend of Tenna)": "鑰匙 (Tenna傳說)",
  Q: "Q",
  "Lancer (The Legend of Tenna)": "Lancer (Tenna傳說)",
  "Mooncloud Stone": "月雲石",
  "Power Croissant": "力量可頌",
  Camera: "相機",
  "Grand Photo": "特級照片",
  "Lanino (The Legend of Tenna)": "Lanino (Tenna傳說)",
  "Elnina (The Legend of Tenna)": "Elnina (Tenna傳說)",
  "Rouxls Block": "Rouxls的方塊",
  "Ribbon (The Legend of Tenna)": "緞帶 (Tenna傳說)",
  "Pizza Deodorant (For Nerds)": "披薩除臭劑 (呆瓜專用)",
  "Sword (Original Game)": "劍 (原版遊戲)",
  "Ice Key": "冰之鑰",
  "Shelter Key": "庇護所鑰匙",
  "Ball of Junk": "垃圾球",
  "Hot Chocolate": "熱巧克力",
  Bouquet: "花束",
  Cards: "撲克牌",
  "Box of Heart Candy": "心形巧克力",
  "Honey Toast": "面包",
  Seeds: "种子",
  Glass: "玻璃",
  Glowshard: "發光碎片",
  Manual: "手冊",
  EverybodyWeapon: "大家武器",
  GigaSalad: "巨大沙拉",
  FavSandwich: "讚明治",
  MouseToken: "鼠幣",
  Trefoil: "三葉劍",
  "Life Dew": "生命露水",
  PureCrystal: "純淨水晶",
  TwistedSwd: "扭曲之劍",
  SkyMantle: "蒼穹斗篷",
  CheerScarf: "啦啦隊圍巾",
  SpikeShackle: "尖刺鐐銬",
  DarkGoldBand: "黑金臂环",
  JavaCookie: "Java餅乾",
  ReviveBrite: "復活片",
  BackstagePass: "後台通行證",
  "Mooncloud Key Card": "月雲門禁卡",
  "Elnina's controller": "Elnina的手柄",
  Hookshot: "鉤爪",
  Voucher: "代金券",
  "Bucket of POINTs": "點數桶",
  Schadenbrot: "破损的面包",
  GildedRose: "镀金玫瑰",
  "Pink Coin": "粉钱",
  "Flowery dollar": "Flowery币",
  // ==================== Deltarune 机制、杂项 ====================  " ": " ",
  "7 Colored Flowers": "七色花",
  "Favorite Sandwich": "赞明治",
  Favwich: "赞明治",
  KrisTea: "Kris茶",
  SusieTea: "Susie茶",
  RalseiTea: "Ralsei茶",
  NoelleTea: "Noelle茶",
  RottenTea: "变质的茶",
  "Ancient Chocolate": "远古巧克力",
  "Double-Dark-burger": "双层黑暗汉堡",
  ButJuice: "管汁",
  BrokenSword: "断掉的剑",
  BrockenScarf: "破围巾",
  GlidedRose: "镀金玫瑰",
  MechanicalPencil: "自动铅笔",
  HalloweenPencil: "万圣节铅笔",
  QuillPen: "羽毛笔",
  Eraser: "橡皮",
  LuckyPencil: "幸运铅笔",
  Wristwatch: "手表",
  Petal: "花瓣",
  Pacify: "安抚",
  "Heal Prayer": "治疗祷言",
  DualHeal: "双重治疗",
  FluffyGuard: "毛毛守护",
  ReviveKris: "复活Kris",
  RedBuster: "朱红碎击",
  DualBuster: "双重碎击",
  WakeKris: "唤醒Kris",
  UltimateHeal: "终极治疗",
  UltraHeal: "究极治疗",
  OKHeal: "OK治疗",
  BetterHeal: "进阶治疗",
  "Super Charging": "超级充能",
  IceShock: "冰震术",
  FireShock: "火震术",
  "Sleep Mist": "睡眠迷雾",
  SnowGrave: "雪葬",
  "Rude Sword": "粗暴剑法",
  "Thrash Mechine": "揍人机",
  "Roaring Knight": "呼啸骑士",
  Caller: "来电者",
  Watercooler: "饮水机",
  HolywaterCooler: "圣水机",
  "White Cloak": "白袍之人",
  "Sound of Justice": "正义之声",
  "Titan Spawn": "泰坦胚胎",
  Man: "男人",
  "Annoying Dog": "神烦狗",
  Lightners: "光之民",
  Darkners: "暗之民",
  "Light World": "光世界",
  "Dark World": "暗世界",
  Human: "人类",
  Monster: "怪物",
  "Shortcut door": "传送门",
  Dollar: "元",
  $: "$",
  "Dark Dollar": "黑暗币",
  D$: "D$",
  POINTs: "点数",
  PTs: "点数",
  Elements: "属性",
  Shadow: "暗影",
  Devil: "恶魔",
  Dust: "尘埃",
  Determination: "决心",
  SOUL: "灵魂",
  seal: "封印",
  AT: "攻击力",
  DF: "防御力",
  MAGIC: "魔力值",
  FIGHT: "战斗",
  ACT: "行动",
  SPELL: "法术",
  ITEM: "物品",
  SPARE: "饶恕",
  DEFENSE: "防御",
  Encounter: "遭遇战",
  "Bullet board": "战斗框",
  Stats: "状态",
  "The Roaring": "【呼啸】",
  Deltarune: "Deltarune",
  "Delta Rune": "三角符文",
  DELTARUNE: "【三角符文】",
  "chapter 1": "第一章",
  "chapter 2": "第二章",
  "chapter 3": "第三章",
  "chapter 4": "第四章",
  "chapter 5": "第五章",
  "chapter 6": "第六章",
  "chapter 7": "第七章",
  Storage: "库存",
  DogDollar: "狗币",
  "Save point": "存档点",
  "Pacifist route": "招揽线",
  Recruit: "招揽",
  LOST: "失去",
  "= Description =": "= 描述 =",
  "= Profile =": "= 个人档案 =",
  "= Personality =": "= 个性 =",
  "= Main Story =": "= 主要故事 =",
  "= In-battle =": "= 战斗中 =",
  "= Relationship =": "= 关系 =",
  "= Additional Use =": "= 额外用途 =",
  "= Quote =": "=台词=",
  "= Flavor Text =": "= 文本 =",
  "= Trivia =": "= 其他 =",
  "= gallery =": "= 画廊 =",
  "= References =": "= 参考 =",
  "= In battle =": "= 战斗中 =",
  "= Attacks =": "= 攻击 =",
  "= Appearance =": "= 外貌 =",
  "= Appears with =": "= 一起出现 =",
  "= Strategy =": "= 策略 =",
  "= Quotes =": "= 台词 =",
  Character: "角色",
  Enemies: "敌人",
  Boss: "头目",
  Location: "地点",
  SoundTrack: "原声带",
  Vendors: "商店",
  Items: "物品",
  "Consumable items": "消耗品",
  "Gameplay Mechanics": "游戏机制",
  "Plot Elements": "戏情元素",
  "Navbox characters": "角色列表",
  "Navbox locations": "地点列表",
  "Navbox items": "物品列表",
  "Navbox elements": "机制列表",
  "Infobox character": "角色",
  "Infobox location": "地点",
  "Infobox item": "物品",
  "Infobox element": "机制元素",
  "Weird Route": "怪异路线",
  Dogcheck: "坏档狗",

  // ==================== Deltarune 原声带（所有章节） ====================
  // Chapter 1
  "ANOTHER HIM": "另一個他",
  Beginning: "開始",
  "School (soundtrack)": "學校 (原聲帶)",
  "Susie (soundtrack)": "Susie (原聲帶)",
  "The Door": "門",
  "Cliffs (soundtrack)": "懸崖 (原聲帶)",
  "The Chase": "追逐",
  "The Legend": "傳說",
  "Lancer (soundtrack)": "Lancer (原聲帶)",
  "Rude Buster (soundtrack)": "粗暴碎擊 (原聲帶)",
  "Empty Town": "空蕩蕩的小鎮",
  "Weird Birds": "奇怪的鳥兒",
  "Field of Hopes and Dreams": "希望與夢想之原",
  "Fanfare (from Rose of Winter)": "大張旗鼓 (來自Rose of Winter)",
  Lantern: "燈火",
  "I'm Very Bad": "我超級壞的",
  "Checker Dance": "跳棋之舞",
  "Quiet Autumn": "寧靜之秋",
  "Scarlet Forest": "猩红森林",
  "Thrash Machine (soundtrack)": "揍人機 (原聲帶)",
  "Vs. Lancer": "Vs. Lancer",
  "Basement (soundtrack)": "地牢 (原聲帶)",
  "Imminent Death": "死亡迫近",
  "Vs. Susie": "Vs. Susie",
  "Card Castle (soundtrack)": "撲克城堡 (原聲帶)",
  "Rouxls Kaard (soundtrack)": "Rouxls Kaard (原聲帶)",
  "April 2012": "2012年4月",
  "Hip Shop": "嘻哈商店",
  Gallery: "屋頂",
  "Chaos King": "混沌之王",
  "Darkness Falls": "黑暗降臨",
  "The Circus": "馬戲團",
  "THE WORLD REVOLVING": "天旋地轉",
  Friendship: "友誼",
  "THE HOLY": "神聖的",
  "Your Power": "你的力量",
  "A Town Called Hometown": "名叫家鄉的小鎮",
  "You Can Always Come Home": "你總是能回家",
  "Don't Forget": "別忘記",
  "Before the Story": "故事之前",

  // Chapter 2
  "Faint Glow": "微弱光芒",
  "Girl Next Door": "鄰家女孩",
  "My Castle Town": "我的城堡鎮",
  "Ohhhhohohoho!": "喔吼吼吼吼吼吼！",
  "Queen (soundtrack)": "女王 (原聲帶)",
  "A CYBER'S WORLD?": "賽博世界？",
  "A Simple Diversion": "簡單的消遣",
  "Almost To The Guys!": "夥計們馬上到！",
  "Cool Beat": "炫酷節拍",
  "When I Get Mad I Dance Like This": "我生氣時會這樣跳舞",
  "Cyber Battle (Solo)": "賽博戰鬥 (獨奏)",
  "When I Get Happy I Dance Like This": "我高興時會這樣跳舞",
  "Sound Studio": "聲音錄音棚",
  "Berdly (soundtrack)": "Berdly (原聲帶)",
  "Smart Race": "智力大比拼",
  "Faint Courage (Game Over)": "微弱勇氣 (遊戲結束)",
  "WELCOME TO THE CITY": "歡迎來到城市",
  "Mini Studio": "迷你錄音棚",
  "Holiday Studio": "假日錄音棚",
  "Cool Mixtape": "炫酷混音帶",
  "HEY EVERY !": "大家 好啊 ！",
  "Spamton (soundtrack)": "Spamton (原聲帶)",
  "NOW'S YOUR CHANCE TO BE A": "現在是你的絕佳時機",
  "Elegant Entrance": "優雅的入口",
  "Bluebird of Misfortune": "不幸的藍鳥",
  "Pandora Palace": "潘多拉皇宮",
  KEYGEN: "密鑰生成器",
  "Acid Tunnel of Love": "愛的酸液隧道",
  'It\'s Pronounced "Rules"': "讀作“規則”",
  "Lost Girl": "迷失的女孩",
  "Ferris Wheel": "摩天輪",
  "Attack of the Killer Queen": "殺手女王的進攻",
  "Giga Size": "千兆大小",
  "Powers Combined": "能量合體",
  "Knock You Down !!": "將你擊倒！！",
  "The Dark Truth": "黑暗的真相",
  "Digital Roots": "數根",
  "Deal Gone Wrong": "交易出錯",
  "BIG SHOT": "大人物",
  "A Real Boy!": "真正的男孩！",
  Dialtone: "撥號音",
  "sans.": "Sans.",
  "Chill Jailbreak Alarm To Study And Relax To": "適合學習和放鬆時聽的越獄警報",
  "Until Next Time": "下次見",
  "Berdly (Rejected Concept)": "Berdly (被拒絕的概念)",

  // Chapters 3+4
  "Flashback (Excerpt)": "回憶片段 (節錄)",
  "Feature Presentation": "正片開始",
  "And Now For Today's Sponsors...!": "現在有請今天的贊助商...！",
  "MIKE, the BOARD, please!": "MIKE，請上圖版！",
  "Sandy Board": "沙地圖版",
  "Adventure Board": "冒險圖版",
  "Query?": "提問？",
  "Quiz!": "測驗！",
  "Dig! Dig! To The Center of the Earth!": "挖啊！挖啊！直達地心！",
  "Pushing Buddies": "夥伴推推",
  "Ruder Buster": "更粗暴碎擊",
  "Physical Challenge": "體能大挑戰",
  "Board Clear!": "圖版過關！",
  "Welcome to the Green Room": "歡迎來到休息室",
  "Vapor Buster": "蒸氣碎擊",
  "Paradise, Paradise": "樂園，樂園",
  "Raft Ride": "木筏之旅",
  "SOUTH OF THE BORDER!!": "南方邊界風情！！",
  "Sound Check": "音效檢查",
  "Raise Up Your Bat": "舉起你的球棒",
  "KING OF ROLYPOLY": "ROLYPOLY之王",
  "Glowing Snow": "發光雪花",
  "Big City Board": "大城市圖版",
  "Doom Board": "毀滅圖版",
  "Metaphysical Challenge": "超脫大挑戰",
  "TV WORLD (soundtrack)": "TV世界 (原聲帶)",
  "It's TV Time!": "現在是TV時間！",
  "Hall of Fame": "名人堂",
  Breath: "呼吸",
  "Black Knife": "黑刃",
  Crickets: "蟋蟀",
  Dump: "垃圾場",
  SWORD: "劍",
  NORTHERNLIGHT: "北境極光",
  GLACEIR: "冰川",
  "BIT ROOTS": "位元根",
  ERAM: "魘",
  "BURNING EYES": "燃燒之眼",
  "Old wooden rafters": "老舊木椽",
  Hymn: "聖詠",
  "Another day in hometown": "家鄉鎮的另一天",
  Friends: "朋友們",
  "Castle Funk": "城堡放克",
  "Knock You Down!! (Rhythm Ver.)": "將你擊倒！！(節奏版)",
  "Gingerbread House": "薑餅屋",
  "The distance between two": "兩人之間的距離",
  "C (soundtrack)": "C (原聲帶)",
  ATRIUM: "中庭",
  "Dark Sanctuary (soundtrack)": "黑暗聖域 (原聲帶)",
  "From Now On (Battle 2)": "從今以後 (戰鬥2)",
  "Gyaa Ha ha!": "噶哈哈！",
  Fireplace: "壁爐",
  "A DARK ZONE": "黑暗區域",
  "Mysterious Ringing": "神祕鐘聲",
  "Ever Higher": "越來越高",
  "Wise words": "智者之語",
  "Piano that may not be played that well": "可能彈得不是很好的鋼琴曲",
  "Hammer of Justice (soundtrack)": "正義之錘 (原聲帶)",
  "12am": "午夜12點",
  "The Second Sanctuary": "第二聖域",
  Ripple: "漣漪",
  "13am": "午夜13點",
  "The Third Sanctuary": "第三聖域",
  "Dark Place": "黑暗之地",
  "Heavy Footsteps": "沉重的腳步聲",
  "Crumbling Tower": "崩毀的高塔",
  SPAWN: "產物",
  GUARDIAN: "守護者",
  "Need a hand!?": "需要幫忙嗎！？",
  "The place where it rained": "此處剛在下雨",
  "The Ol' Jitterbug": "老吉魯巴舞",
  "Neverending Night": "無盡之夜",
  "The LEGEND...?": "傳說...？",
  "With Hope Crossed On Our Hearts": "心中滿懷希望",
  "Volume Adjustment": "音量調整",
  Catswing: "搖擺貓貓",
  AIRWAVES: "空氣波",
  "Concert for you": "為你演奏的音樂會",

  // Chapter 5
  "Chapter 5 Logo": "第五章標題畫面",
  "Inappropriate Recycling": "不當回收",
  "Pirate Dojo": "海盜道館",
  "4rd Sanctuary": "第亖聖域",
  "Festival (soundtrack)": "慶典 (原聲帶)",
  "Catfession...?": "告白喵...？",
  "Bratfession...?": "告白Brat...？",
  "I guess I'm in love": "我想我已墜入愛河",
  "Weirder Birds": "更奇怪的鳥兒",
  "Your Dad's Best Friend": "你爸爸最好的朋友",
  "Garden of Hopes and Dreams": "希望與夢想之園",
  "Rakuichi Buster": "Rakuichi碎擊",
  "The Diner Song of Best Friends": "最好朋友的餐廳之歌",
  "Ride the Board": "滑板騎行",
  "Quiet Glade": "靜謐林間空地",
  "Who might you be?": "你會是誰呢？",
  "Petal Dance": "花瓣之舞",
  "Flying Feather": "飛羽",
  "Sunset of Seven Suns": "七顆太陽的日落",
  "Shop 3": "商店3",
  "Violet Tactics": "紫羅蘭戰術",
  "Flower King (soundtrack)": "花王 (原聲帶)",
  "Flower Foyer": "花城玄關",
  "Flower Castle (soundtrack)": "花之城堡 (原聲帶)",
  "Thousand Cafe Zukan": "萬千咖啡館圖鑑",
  "I'm Telling!": "我要告狀！",
  "Stop, Criminell!": "站住，罪犯分子！",
  "Loving Steps": "愛的舞步",
  Onsen: "溫泉",
  "Beautiful Bathtime": "美妙的沐浴時光",
  "Pink (soundtrack)": "Pink (原聲帶)",
  "Cutie Mew Mew Magic": "可愛喵喵魔法",
  "Running Sky": "奔馳的天空",
  "Flower Man": "小花俠",
  "That Day": "那一天",
  Dreamwatchers: "夢想見證者",
  "Weak Flowers": "弱小的花朵",
  "Walking Home": "回家路上",
  "Field of Hopes and Dreams (Credits Version)": "希望與夢想之原 (職員表版)",
  "Goodnight, Sweet Prince": "晚安，親愛的王子",
};

const utyMap = {
  // 绝对翻译的人物
  "North Star": "北极星",
  "Feisty Four": "活力四人组",
  "Feisty Five": "活力五人组",
  // ==================== Undertale Yellow 地点 ====================
  Ruins: "废墟",
  "Dark Ruins": "黑暗废墟",
  Snowdin: "雪町",
  "Honeydew Resort": "蜜露度假村",
  Dunes: "沙丘",
  "East Mines": "东部矿井",
  "Oasis Valley": "绿洲山谷",
  "Café Dune": "沙丘咖啡馆",
  Estate: "Ketsukane 宅邸",
  "Wild East": "狂野东方",
  "Sunnyside Farm": "晴畔农场",
  Steamworks: "蒸汽工厂",
  Greenhouse: "温室",
  "Factory Wing": "工厂",
  "Chemistry Wing": "实验室",
  Hotland: "热地",
  "UG Apartments": "地下公寓",
  "New Home": "新家",
  Waterfall: "瀑布",
  Meadow: "草地",

  // ==================== Undertale Yellow 消耗品 ====================
  Lemonade: "柠檬水",
  "Candy Corn": "玉米糖",
  "Corn Dog": "玉米狗",
  "Sponge Cake": "海绵蛋糕",
  "Hot Pop": "热冰棒",
  "Lukewarm Pop": "温热冰棒",
  "Cold Pop": "冷冻冰棒",
  "Honeydew Coffee": "蜜露咖啡",
  "Honeydew Pancake": "蜜露松饼",
  "G.B. Bear": "姜饼熊",
  "Packing Peanuts": "化工生物塑料",
  "Trail Mix": "混合干果",
  "Ice Tea": "冰茶",
  "Green Tea": "绿茶",
  "Sea Tea": "海茶",
  Fruitcake: "水果蛋糕",
  "Spider Donut": "蜘蛛甜甜圈",
  Icewater: "冰水",
  "Root Beer": "根汁啤酒",
  "Feisty Slider": "活力滑堡",
  Gunpowder: "火药",
  "Adult Soda": "成人苏打水",
  "Moss Salad": "苔藓沙拉",
  "Grassy Fries": "生草薯条",
  "Flower Stew": "花花炖菜",
  "Gravity Granola": "重力谷麦",
  "Dihydrogen Monoxide": "一氧化二氢",
  "Popato Chisps": "薯片",
  "Beef Jerky": "牛肉干",
  Cake: "蛋糕",
  "Monster Candy": "怪物糖果",
  "Monster Candy+": "怪物糖果+",
  "Corn Chowder": "玉米浓汤",
  "Hot Dog": "热狗",
  "Cinnamon-Butterscotch Strudel": "糖桂卷饼",
  "Floral Cupcake": "花卉纸杯蛋糕",
  "Cinnamon Cookie": "肉桂曲奇",
  "Oasis Latte": "绿洲拿铁",
  "Golden Pear": "黄金梨子",
  "Golden Coffee": "金咖啡",
  "Golden Cactus": "金人掌",

  // ==================== Undertale Yellow 饰品 ====================
  Patch: "布料",
  Feather: "羽毛",
  "Honeydew Pin": "蜜露饰针",
  "Band Merch Pin": "乐队饰针",
  "Safety Jacket": "反光背心",
  "Steel Buckle": "钢扣",
  "Fancy Holster": "精致枪套",
  "Safety Goggles": "安全护目镜",
  "Silver Scarf": "银色围巾",
  "Golden Bandana": "金方巾",
  "Delta Rune Patch": "三角符文徽章",

  // ==================== Undertale Yellow 弹药 ====================
  "Rubber Ammo": "橡胶子弹",
  Pebbles: "小石子子弹",
  "Ice Pellets": "冰弹",
  "Coffee Bean Ammo": "咖啡子弹",
  "Glass Ammo": "玻璃子弹",
  "Flint Ammo": "燧石子弹",
  "Silver Ammo": "银制子弹",
  Nails: "钉子",
  "Friendliness Pellets": "友谊颗粒",

  // ==================== Undertale Yellow 武器 ====================
  "Toy Gun": "玩具枪",
  "Wild Revolver": "狂野左轮",

  // ==================== Undertale Yellow 装备 ====================
  "Worn Hat": "破旧帽子",
  "Nice Hat": "漂亮帽子",

  // ==================== Undertale Yellow 杂项 ====================
  "Missing Poster": "寻人启事",
  "Snowdin Map": "雪町地图",
  Matches: "火柴",
  "Lukewarm Coffee": "温热咖啡",
  "Soggy Mitten": "潮湿手套",
  Necklace: "项链",
  Pickaxe: "镐子",
  "Hydrochloric Acid": "盐酸",
  Videotape: "录像带",
  "Mail Whale": "邮件鲸鱼",

  // ==================== Undertale Yellow 未出现物品 ====================
  "Homemade Cookie": "手工饼干",
  "Golden Scarf": "金色围巾",
  "Super Ammo": "超级子弹",
  "Toy Knife": "玩具刀",

  // ==================== Undertale Yellow 游戏机制 ====================
  "Dimensional Box": "次元箱",
  GOLD: "金钱",
  SAVE: "存档",
  "Game Config": "设定目录",
  "Fun value": "Fun 值",
  UGPS: "地邮",

  // ==================== Undertale Yellow 剧情机制 ====================
  "Underground Postal Service": "地底邮政服务",
  Gemstones: "宝石",
  Serum: "血清",
  Gemstones: "炽热石",

  // ==================== Undertale Yellow 原声带 ====================
  "Once Upon a Truthful Time": "很久很久以前的真實故事",
  "Main Menu 1 (Ruins)": "主選單 1 (廢墟)",
  "Making Adjustments": "做些調整",
  "Enemy Approaching (Yellow)": "敵人接近 (黃色)",
  "Fallen Down (Yellow)": "墜落 (黃色)",
  "Ruins (Yellow)": "廢墟 (黃色)",
  "Howdy!": "哈囉！",
  "Main Menu 2 (Dark Ruins)": "主選單 2 (黑暗廢墟)",
  "In Darkness": "於黑暗中",
  Justice: "正義",
  "Fever Pitch": "白熱化",
  Seclusion: "隱居",
  "Fun-Sized": "迷你版的樂趣",
  Forlorn: "孤寂",
  "House Guest": "房客",
  "Organ Demo": "示範風琴",
  Snowfall: "降雪",
  "Main Menu 3 (Snowdin)": "主選單 3 (雪町)",
  "Blizzard Approaching": "暴風雪逼近",
  "Birds of a Feather": "物以類聚",
  "Mo Money": "更 Mo 的錢",
  "Delivery!": "送貨！",
  "Occupied Turf": "佔領的地盤",
  Shuffling: "洗牌",
  Relaxation: "放鬆",
  "Honeydew Cabin": "蜜露小屋",
  "Honeydew Snow": "蜜露雪花",
  "Honeydew Ruins": "蜜露廢墟",
  "Honeydew Hideaway": "蜜露隱士",
  "Honeydew Bark": "蜜露汪汪",
  Protocol: "協議",
  Aviation: "航空",
  "Quiet Stray": "安靜的流浪者",
  "Main Menu 4 (Dunes)": "主選單 4 (沙丘)",
  "Vigorous Terrain": "崎嶇地形",
  "Sandstorm Approaching": "沙塵暴逼近",
  "Mining Co. (soundtrack)": "礦業公司 (原聲帶)",
  "Gemstone Fever": "寶石狂熱",
  "Going Up": "上升",
  "Mining Co-ncussion": "礦業腦震盪",
  Shimmer: "微光",
  Apex: "頂點",
  "¡Qué Pasión!": "多麼熱情！",
  DANZA: "舞起來",
  "Oasis Valley (soundtrack)": "綠洲谷 (原聲帶)",
  "Oasis Valley (Indoors)": "綠洲谷 (室內)",
  "Café Dune (soundtrack)": "沙丘咖啡館 (原聲帶)",
  "ラブ･ブラスター!": "ラブ･ブラスター！",
  "フィナーレ!": "フィナーレ！",
  "North Star (soundtrack)": "北極星 (原聲帶)",
  "Feisty!": "好鬥！",
  "A New Partner": "新夥伴",
  "Happy Hour": "快樂時光",
  Blossom: "綻放",
  "The Wild East": "狂野東方 (原聲帶)",
  "The Stable": "馬廄",
  "The Clinic": "診所",
  "The Slammer": "監獄",
  "The House": "房屋",
  "Six-Shooter (soundtrack)": "六發左輪 (原聲帶)",
  "A Teaspoon of Gunpowder": "一茶匙火藥",
  "Dual!": "決鬥！",
  "Sheriff's Fate": "警長的命運",
  "Nap Time": "小睡時間",
  "Someone's In Danger!": "有人有危險！",
  "The Train Problem": "火車難題",
  "Deal 'Em Out": "發牌吧",
  "The Straw": "稻草",
  "Getting the Thoughts Out": "釋放思緒",
  "Showdown!": "決戰！",
  Renewed: "重振",
  "Sunnyside Farm (soundtrack)": "晴畔農場 (原聲帶)",
  "Kanako (soundtrack)": "Kanako (原聲帶)",
  "Change of Plans": "計畫有變",
  "Tomorrow Means The Surface": "明天意味著地表",
  "Main Menu 5 (Steamworks)": "主選單 5 (蒸汽工廠)",
  "Meltdown": "熔毀",
  "Treading Lightly": "小心行事",
  "Enter Axis": "進入軸心",
  "Detainment 014": "拘留 014",
  "Build-A-Bot": "造一個機器人",
  "Heatwave Approaching": "熱浪逼近",
  "Golden Opportunity": "黃金機會",
  "Through the Macro Lens": "透過微距鏡頭",
  "FOUND YOU.": "找到你了。",
  "The Corner of a Circle": "圓的角落",
  "After Hours": "下班後",
  "Greenhouse_(soundtrack)": "溫室 (原聲帶)",
  "TENTH LEVEL LOCKDOWN": "第十層封鎖",
  "Mixin' It Up": "混搭一下",
  "One's Past...": "某人的過去...",
  "Guns Blazing": "真槍實彈",
  Soulmate_Located: "找到靈魂伴侶",
  "The Freedom to be Flawed": "不完美的自由",
  Medium: "媒介",
  "UG Apartments (soundtrack)": "地下公寓 (原聲帶)",
  "An Acquittal": "無罪釋放",
  "The Flower": "花",
  "You Gotta Be Kidding Me!": "你在開玩笑吧！",
  "just us": "只有我們",
  "echoes of another": "他者的回聲",
  "BEST FRIENDS FOREVER": "永遠的好朋友",
  subconscious: "潛意識",
  snow: "雪",
  crescendo: "漸強",
  "gotcha ;)": "抓到你了 ;)",
  AFTERLIFE: "來世",
  "specimen: patchworked": "樣本：拼接",
  "specimen: organic": "樣本：有機",
  "specimen: clay": "樣本：黏土",
  "specimen: paper": "樣本：紙片",
  "specimen: polygonal": "樣本：多邊形",
  "specimen: mechanical": "樣本：機械",
  "The Trek": "長途跋涉",
  Trapdoor: "暗門",
  "Nothing but the Truth": "唯有真相",
  "Flock Together": "群聚同行",
  "Kanako (Reprise)": "Kanako (重奏版)",
  "Some Point of No Return": "某個無法回頭的時刻",
  "A Mother's Love": "母愛",
  "Tucked In": "被安頓好",
  Gift: "禮物",
  "Undertale Yellow (soundtrack)": "Undertale Yellow (原聲帶)",
  "A Place to Rest": "休息之處",
  "A Call to Action": "行動號召",
  "Final Encounter": "最終遭遇",
  "Enemy Retreating": "敵人撤退",
  Apprehension: "憂慮",
  "Orange Skies": "橘色天空",
  "Trial By Fury": "憤怒的審判",
  "END OF THE LINE_": "終點",
  Remedy: "療方",
  Retribution: "報應",
  "Honest Days Work": "誠實的一天工作",
  Adjourned: "休會",
  "= Description =": "= 描述 =",
  "= Features =": "= 区域要素 =",
  "= Profile =": "= 个人档案 =",
  "= Personality =": "= 个性 =",
  "= Main Story =": "= 主要故事 =",
  "= In-battle =": "= 战斗中 =",
  "= Relationship =": "= 关系 =",
  "= Additional Use =": "= 额外用途 =",
  "= Quote =": "=台词=",
  "= Flavor Text =": "= 文本 =",
  "= Trivia =": "= 其他 =",
  "= gallery =": "= 画廊 =",
  "= References =": "= 参考 =",
  "= Pacifist Route =": "= 和平路线 =",
  "= Genocide Route =": "= 屠杀路线 =",
  "= Neutral Route =": "= 普通路线 =",
  "= In battle =": "= 战斗中 =",
  "= Attacks =": "= 攻击 =",
  "= Appearance =": "= 外貌 =",
  "= Appears with =": "= 一起出现 =",
  "= Strategy =": "= 策略 =",
  "= Quotes =": "= 台词 =",
  "= Map =": "= 地图 =",
  "= Geography =": "= 地理 =",
  "= Creation and development =": "= 创作和开发 =",
  "= Devlogs =": "= 开发日志 =",
  "= aftermath =": "= 余波 =",
  "Scripted Encounter": "剧情遭遇",
  "Scripted encounter": "剧情遭遇",
  Boss: "头目",
  Vendor: "商店",
  Item: "物品",
  "Consumable items": "消耗品",
  "Gameplay Mechanics": "游戏机制",
  "Plot Elements": "戏情元素",
  "Navbox characters": "角色列表",
  "Navbox locations": "地点列表",
  "Navbox items": "物品列表",
  "Navbox elements": "机制列表",
  "Infobox character": "角色",
  "Infobox location": "地点",
  "Infobox item": "物品",
  "Infobox element": "机制元素",
};
