const drMap = {
  // ==================== 分类（Category）名称 ====================
  Enemies: "敌人",
  Boss: "头目",
  Location: "地点",
  SoundTrack: "原声带",
  Vendors: "商店",
  Items: "物品",
  "Consumable items": "消耗品",
  Dog: "狗",
  "Gameplay Mechanics": "游戏机制",
  "Plot Elements": "戏情元素",
  Ending: "结局",
  "Neutral Route": "中立路线",
  "Genocide Route": "屠杀路线",
  "Pacifist Route": "完美路线",
  "Eight Human": "八名人类",

  // ==================== Deltarune 地点 ====================
  Hometown: "家乡镇",
  "Dreemurr residence": "Dreemurr家",
  School: "学校",
  Library: "图书馆",
  Hospital: "医院",
  "QC's Diner": "QC餐厅",
  "Town Hall": "市政厅",
  Shelter: "避难所",
  Church: "教堂",
  "'Sans": "'Sans便利店",
  "Noelle's House": "Holiday宅邸",
  "Closet Dark World": "学校储物间",
  "Party Dojo": "派对道场",
  "Ralsei's castle": "Ralsei的城堡",
  "TV Studio": "TV演播室",
  Field: "平原",
  Forest: "森林",
  "Card Castle": "扑克城堡",
  "Cyber Field": "赛博平原",
  "Cyber City": "赛博城市",
  "Queen's Mansion": "女王的豪宅",
  "TV World": "TV世界",
  "Couch cliffs": "沙发悬崖",
  "Green Room": "休息室",
  "Cold Place": "极寒之地",
  Mancountry: "男人国",
  "Desert Board": "沙漠图版",
  "Island Board": "岛屿图版",
  "Ice Palace": "冰宫",
  "City Board (Original Game)": "城市图版 (原版游戏)",
  "City Board (The Legend of Tenna)": "城市图版 (《Tenna传说》)",
  "Manhole dungeon": "下水道地牢",
  "Dark Sanctuaries": "三黑暗圣域",
  "Dark Sanctuary (Study)": "黑暗圣域 (书房)",
  "2nd Sanctuary": "第二圣域",
  "3rd Sanctuary": "第三圣域",
  "Flower Kingdom": "花之王国",
  Garden: "花园",
  Cliffs: "悬崖",
  "Flower Castle (Flower Cafe)": "花之城堡 (花之咖啡馆)",
  "Top of Castle": "城堡顶层",
  Unused: "未使用",
  "Flower King": "花王",
  'ICE-E\'s P"E"ZZA': "ICE-E的披“E”萨店",
  "Police Station": "警察局",
  Lake: "湖",
  Cafe: "咖啡馆",
  "Top Bakery": "顶级面包店",
  "The Legend of Tenna": "《Tenna传说》",
  "Original Game": "原版游戏",
  "Wet-Nose Bandits": "湿鼻子大盗",
  // ==================== 新增物品、装备、机制等（按原列表顺序） ====================
  "Dark Candy": "黑暗糖果",
  Darkburger: "黑暗漢堡",
  "Choco Diamond": "方鑽巧克力",
  "Hearts Donut": "紅心甜甜圈",
  "Lancer Cookie": "Lancer餅乾",
  "Top Cake": "頂尖蛋糕",
  SpinCake: "旋轉蛋糕",
  ReviveMint: "復活薄荷",
  ClubsSandwich: "梅花三明治",
  RouxlsRoux: "Rouxls油麵醬",
  LightCandy: "光明糖果",
  "DD-Burger": "双黑堡",
  "CD Bagel": "CD貝果",
  TensionBit: "緊迫一點",
  Tea: "茶",
  SpagettiCode: "意面代码",
  "S.POISON": "S.毒藥",
  ReviveDust: "復活粉",
  TensionGem: "緊迫寶石",
  "TV Dinner": "電視餐",
  DeluxeDinner: "高檔餐",
  TVSlop: "電視糊糊",
  TensionMax: "緊迫滿點",
  ExecBuffet: "精英自助餐",
  "Pipis (item)": "Pipis (物品)",
  FlatSoda: "跑氣的汽水",
  "Darker Candy": "深暗糖果",
  AncientSweet: "遠古甜點",
  Rhapsotea: "狂想茶",
  Scarlixir: "緋紅靈藥",
  BitterTear: "苦澀眼淚",
  PunchBowl: "全碗潘趣",
  "S.POTION": "S.补药",
  GreenTea: "Green茶",
  OrangeJuice: "Orange果汁",
  Flavigne: "友怡颗粒",
  TreeCake: "年轮蛋糕",
  "Raw Moon": "梦芬达",
  Phanta: "潭珠汽水",
  FlowerySoda: "Flowery汽水",
  Shikacola: "鹿可乐",
  "Wood Blade": "木劍",
  Spookysword: "駭人的劍",
  MechaSaber: "機甲軍刀",
  BounceBlade: "彈彈劍",
  Saber10: "刺刀10",
  BlackShard: "黑色碎片",
  JingleBlade: "叮噹劍",
  "Winglade (item)": "羽翼劍",
  WoodBlade2: "木剑2",
  AquaKnife: "Aqua小刀",
  "Mane Ax": "鬃斧",
  Devilsknife: "惡魔飛刀",
  "Brave Ax": "勇氣之斧",
  AutoAxe: "自動斧",
  ToxicAxe: "劇毒斧",
  AbsorbAx: "吸取之斧",
  JusticeAxe: "正義之斧",
  Thatchet: "棘手斧",
  "Red Scarf": "紅圍巾",
  Ragger: "劈巾",
  DaintyScarf: "精緻圍巾",
  FiberScarf: "纖維圍巾",
  Ragger2: "劈巾2",
  PuppetScarf: "木偶圍巾",
  FlexScarf: "彎扭圍巾",
  ScarfMark: "絲籤圍巾",
  MistleWP: "槲寄生鞭",
  BlueShoes: "Blue舞鞋",
  BrokenScarf: "破围巾",
  SnowRing: "雪花指环",
  FreezeRing: "冰冻指环",
  ThornRing: "荊棘指环",
  BrokenSwd: "斷掉的劍",
  FloweryScarf: "Flowery围巾",
  Bandage: "创可贴",
  "White Ribbon": "白色緞帶",
  "Amber Card": "琥珀卡片",
  "Dice Brace": "骰子手鍊",
  IronShackle: "鐵製鐐銬",
  Jevilstail: "Jevil的尾巴",
  "Silver Card": "白銀卡片",
  GlowWrist: "彩燈手鍊",
  "Silver Watch": "銀色手錶",
  RoyalPin: "皇室胸針",
  "Pink Ribbon": "粉色緞帶",
  Mannequin: "假人模特",
  "B.ShotBowtie": "大××領結",
  FrayedBowtie: "殘破領結",
  ChainMail: "鏈鎖甲",
  Dealmaker: "成交神器",
  TwinRibbon: "成對緞帶",
  SpikeBand: "尖刺腕帶",
  TensionBow: "緊迫領結",
  LodeStone: "磁石",
  GingerGuard: "薑餅護盾",
  BlueRibbon: "藍色緞帶",
  TennaTie: "Tenna領帶",
  "Shadow Mantle": "暗影斗篷",
  Waferguard: "聖餅護盾",
  MysticBand: "神秘臂環",
  PowerBand: "力量臂環",
  GoldWidow: "金寡婦",
  PrincessRBN: "公主緞帶",
  MonarchRBN: "帝王缎带",
  TrueTie: "真领带",
  DogWidow: "狗寡妇",
  RedRibbon: "红色缎带",
  NetskieHat: "Netskie帽",
  SethSpecs: "Seth眼镜",
  YellowHat: "Yellow帽",
  "O.Glove": "O.手套",
  GreenApron: "Green围裙",
  "Cell Phone": "手機",
  "Broken Cake": "壞掉的蛋糕",
  "Broken Key": "鑰匙碎片",
  Egg: "蛋",
  "Door Key": "牢房鑰匙",
  "Shadow Crystal": "暗影水晶",
  "Lancer (item)": "Lancer (物品)",
  "Rouxls Kaard (item)": "Rouxls Kaard",
  "Starwalker (item)": "Starwalker",
  KeyGen: "密鑰生成器",
  EmptyDisk: "磁碟",
  OddController: "古怪手柄",
  LancerCon: "Lancer手柄",
  TripTicket: "旅行票",
  ClaimbClaws: "爬爬爪",
  SheetMusic: "樂譜",
  "Petal Feather": "花瓣羽毛",
  BromideR: "相卡R",
  YellowKey: "黄色钥匙",
  BlueString: "蓝色细绳",
  YellowShred: "黄色碎布",
  BootOil: "靴油",
  Scissors: "剪刀",
  PerpBook: "紫证书",
  TrainPlan: "轨道设计图",
  RedSplatter: "红色喷溅物",
  MysteryKey: "神秘钥匙",
  BromideF: "相卡F",
  "Key (The Legend of Tenna)": "鑰匙 (Tenna傳說)",
  Q: "Q",
  "Lancer (The Legend of Tenna)": "Lancer (Tenna傳說)",
  "Mooncloud Stone": "月雲石",
  "Power Croissant": "力量可頌",
  Camera: "相機",
  "Grand Photo": "特級照片",
  "Lanino (The Legend of Tenna)": "Lanino (Tenna傳說)",
  "Elnina (The Legend of Tenna)": "Elnina (Tenna傳說)",
  "Rouxls Block": "Rouxls的方塊",
  "Ribbon (The Legend of Tenna)": "緞帶 (Tenna傳說)",
  "Pizza Deodorant (For Nerds)": "披薩除臭劑 (呆瓜專用)",
  "Sword (Original Game)": "劍 (原版遊戲)",
  "Ice Key": "冰之鑰",
  "Shelter Key": "庇護所鑰匙",
  "Ball of Junk": "垃圾球",
  "Hot Chocolate": "熱巧克力",
  Bouquet: "花束",
  Cards: "撲克牌",
  "Box of Heart Candy": "心形巧克力",
  "Honey Toast": "面包",
  Seeds: "种子",
  Glass: "玻璃",
  Glowshard: "發光碎片",
  Manual: "手冊",
  EverybodyWeapon: "大家武器",
  GigaSalad: "巨大沙拉",
  FavSandwich: "讚明治",
  MouseToken: "鼠幣",
  Trefoil: "三葉劍",
  "Life Dew": "生命露水",
  PureCrystal: "純淨水晶",
  TwistedSwd: "扭曲之劍",
  SkyMantle: "蒼穹斗篷",
  CheerScarf: "啦啦隊圍巾",
  SpikeShackle: "尖刺鐐銬",
  DarkGoldBand: "黑金臂环",
  JavaCookie: "Java餅乾",
  ReviveBrite: "復活片",
  BackstagePass: "後台通行證",
  "Mooncloud Key Card": "月雲門禁卡",
  "Elnina's controller": "Elnina的手柄",
  Hookshot: "鉤爪",
  Voucher: "代金券",
  "Bucket of POINTs": "點數桶",
  Schadenbrot: "破损的面包",
  GildedRose: "镀金玫瑰",
  "Pink Coin": "粉钱",
  "Flowery dollar": "Flowery币",
  // ==================== Deltarune 机制、杂项 ====================  " ": " ",
  "7 Colored Flowers": "七色花",
  "Favorite Sandwich": "赞明治",
  Favwich: "赞明治",
  KrisTea: "Kris茶",
  SusieTea: "Susie茶",
  RalseiTea: "Ralsei茶",
  NoelleTea: "Noelle茶",
  RottenTea: "变质的茶",
  "Ancient Chocolate": "远古巧克力",
  "Double-Dark-burger": "双层黑暗汉堡",
  ButJuice: "管汁",
  BrokenSword: "断掉的剑",
  BrockenScarf: "破围巾",
  GlidedRose: "镀金玫瑰",
  MechanicalPencil: "自动铅笔",
  HalloweenPencil: "万圣节铅笔",
  QuillPen: "羽毛笔",
  Eraser: "橡皮",
  LuckyPencil: "幸运铅笔",
  Wristwatch: "手表",
  Petal: "花瓣",
  Pacify: "安抚",
  "Heal Prayer": "治疗祷言",
  DualHeal: "双重治疗",
  FluffyGuard: "毛毛守护",
  ReviveKris: "复活Kris",
  RedBuster: "朱红碎击",
  DualBuster: "双重碎击",
  WakeKris: "唤醒Kris",
  UltimateHeal: "终极治疗",
  UltraHeal: "究极治疗",
  OKHeal: "OK治疗",
  BetterHeal: "进阶治疗",
  "Super Charging": "超级充能",
  IceShock: "冰震术",
  FireShock: "火震术",
  "Sleep Mist": "睡眠迷雾",
  SnowGrave: "雪葬",
  "Rude Sword": "粗暴剑法",
  "Thrash Mechine": "揍人机",
  "Roaring Knight": "呼啸骑士",
  Caller: "来电者",
  Watercooler: "饮水机",
  HolywaterCooler: "圣水机",
  "White Cloak": "白袍之人",
  "Sound of Justice": "正义之声",
  "Titan Spawn": "泰坦胚胎",
  Man: "男人",
  "Annoying Dog": "神烦狗",
  Lightners: "光之民",
  Darkners: "暗之民",
  "Light World": "光世界",
  "Dark World": "暗世界",
  Human: "人类",
  Monster: "怪物",
  "Shortcut door": "传送门",
  Dollar: "元",
  $: "$",
  "Dark Dollar": "黑暗币",
  D$: "D$",
  POINTs: "点数",
  PTs: "点数",
  Elements: "属性",
  Shadow: "暗影",
  Devil: "恶魔",
  Dust: "尘埃",
  Determination: "决心",
  SOUL: "灵魂",
  seal: "封印",
  AT: "攻击力",
  DF: "防御力",
  MAGIC: "魔力值",
  FIGHT: "战斗",
  ACT: "行动",
  SPELL: "法术",
  ITEM: "物品",
  SPARE: "饶恕",
  DEFENSE: "防御",
  Encounter: "遭遇战",
  "Bullet board": "战斗框",
  Stats: "状态",
  "The Roaring": "【呼啸】",
  Deltarune: "Deltarune",
  "Delta Rune": "三角符文",
  DELTARUNE: "【三角符文】",
  "chapter 1": "第一章",
  "chapter 2": "第二章",
  "chapter 3": "第三章",
  "chapter 4": "第四章",
  "chapter 5": "第五章",
  "chapter 6": "第六章",
  "chapter 7": "第七章",
  Storage: "库存",
  DogDollar: "狗币",
  "Save point": "存档点",
  "Pacifist route": "招揽线",
  Recruit: "招揽",
  LOST: "失去",
  "= Description =": "= 描述 =",
  "= Profile =": "= 个人档案 =",
  "= Personality =": "= 个性 =",
  "= Main Story =": "= 主要故事 =",
  "= In-battle =": "= 战斗中 =",
  "= Relationship =": "= 关系 =",
  "= Additional Use =": "= 额外用途 =",
  "= Quote =": "=台词=",
  "= Flavor Text =": "= 文本 =",
  "= Trivia =": "= 其他 =",
  "= gallery =": "= 画廊 =",
  "= References =": "= 参考 =",
  "= In battle =": "= 战斗中 =",
  "= Attacks =": "= 攻击 =",
  "= Appearance =": "= 外貌 =",
  "= Appears with =": "= 一起出现 =",
  "= Strategy =": "= 策略 =",
  "= Quotes =": "= 台词 =",
  Character: "角色",
  Enemies: "敌人",
  Boss: "头目",
  Location: "地点",
  SoundTrack: "原声带",
  Vendors: "商店",
  Items: "物品",
  "Consumable items": "消耗品",
  "Gameplay Mechanics": "游戏机制",
  "Plot Elements": "戏情元素",
  "Navbox characters": "角色列表",
  "Navbox locations": "地点列表",
  "Navbox items": "物品列表",
  "Navbox elements": "机制列表",
  "Infobox character": "角色",
  "Infobox location": "地点",
  "Infobox item": "物品",
  "Infobox element": "机制元素",
  "Weird Route": "怪异路线",
  Dogcheck: "坏档狗",

  // ==================== Deltarune 原声带（所有章节） ====================
  // Chapter 1
  "ANOTHER HIM": "另一個他",
  Beginning: "開始",
  "School (soundtrack)": "學校 (原聲帶)",
  "Susie (soundtrack)": "Susie (原聲帶)",
  "The Door": "門",
  "Cliffs (soundtrack)": "懸崖 (原聲帶)",
  "The Chase": "追逐",
  "The Legend": "傳說",
  "Lancer (soundtrack)": "Lancer (原聲帶)",
  "Rude Buster (soundtrack)": "粗暴碎擊 (原聲帶)",
  "Empty Town": "空蕩蕩的小鎮",
  "Weird Birds": "奇怪的鳥兒",
  "Field of Hopes and Dreams": "希望與夢想之原",
  "Fanfare (from Rose of Winter)": "大張旗鼓 (來自Rose of Winte
